files:
  - source: /docs/EN/*.md
    translation: /docs/%two_letters_code/%original_path%/original_file_name%
  - source: /docs/EN/*.rst
    translation: /docs/%two_letters_code/%original_path%/original_file_name%
  - source: /docs/EN/*/*.md
    translation: /docs/TEST_%two_letters_code%/%original_path%/%original_file_name%
  - source: /docs/EN/*/*.rst
    translation: /docs/TEST_%two_letters_code%/%original_path%/%original_file_name%
